### ISSUE TITLE
AMP Support?

### ISSUE THREAD

**Issue by impiga** [hustvl/YOLOS#18]
Thanks for your great work and releasing the code!

I find that in [engine.py](https://github.com/hustvl/YOLOS/blob/56437ab39be62a6d39eff0989d8e1274480d5fa6/engine.py#L33), AMP-related code is commented out. And I am wondering that if I can use AMP in this project. Would it speed up the training and would it hurt the performance?

**Comment by Yuxin-CV** [comment]
Hi@impiga, thanks for your interests in our work!

We tried torch naive amp, and we observed no significant speed up and acc drop. Please also see https://github.com/facebookresearch/detr/issues/127.

**Comment by impiga** [comment]
Thanks for your response!
