### ISSUE TITLE
About learning rate scheduler

### ISSUE THREAD

**Issue by davidnvq** [hustvl/YOLOS#9]
## ❔Question
From your code `main.py`, I only see the learning rate updated after every epoch: https://github.com/hustvl/YOLOS/blob/2e10dc45b5effc015bd64d597b546caf47fb3c0e/main.py#L217

Looking at your logs, it also seems to confirm that. 
Did you use a warm-up learning rate scheduler for the first few iterations?

**Comment by Yuxin-CV** [comment]
Hello, thanks for your interest in our work.

We don't use warm up during training.

**Comment by davidnvq** [comment]
Thanks for swift reply. I'll close.
